version: '3.8'

services:
  climate-prediction:
    build: .
    container_name: climate-prediction-system
    ports:
      - "8501:8501"  # Streamlit dashboard
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    restart: unless-stopped
    networks:
      - climate-network

volumes:
  data:
  outputs:

networks:
  climate-network:
    driver: bridge